### ISSUE TITLE
Could not load package mews/purifier in http://repo.packagist.org:

### ISSUE THREAD

**Issue by wikigods** [mewebstudio/Purifier#141] opened 2020-09-10 19:57 UTC
Since a few hours I have problems with package and tried in laravel 7 but I get this error

[RuntimeException]
  Could not load package mews/purifier in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ~4.*: Invalid version string "~4.*"

  [UnexpectedValueException]
  Could not parse version constraint ~4.*: Invalid version string "~4.*"

**Comment by bbashel1** [comment] 2020-09-10 20:00
same

**Comment by tpaskett** [comment] 2020-09-10 20:21
same problem here

**Comment by jeremyjaymes** [comment] 2020-09-10 21:59
Running composer self-update fixed the problem for me.

**Comment by wikigods** [comment] 2020-09-10 22:28
Thanks jeremyjaymes it worked

**Comment by lionslair** [comment] 2020-09-11 02:22
same

**Comment by shalinimonad** [comment] 2020-09-11 05:38
same issue

**Comment by amaelftah** [comment] 2020-09-11 06:31
same here too

**Comment by lionslair** [comment] 2020-09-11 06:37
Does anyone understand what the issue is and why updating composer fixes it? Is it some composer.json file change that is only present in newer versions?

**Comment by TriDiamond** [comment] 2020-09-11 07:38
> Running composer self-update fixed the problem for me.

work like a charm thanks!

**Comment by JDsWebService** [comment] 2020-09-11 08:05
> Running composer self-update fixed the problem for me.

Can confirm that this solution works.

For those who are confused. Run the following command, then run composer update

```
$ composer self-update && composer update
```

**Comment by MundaPlus** [comment] 2020-09-11 08:42
Can also confirm the solution, but I needed to do some additional steps. This were my steps, because we have a composer installation done with the package manager of the linux sistem:
`sudo apt-get remove composer
sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
sudo php -r "if (hash_file('sha384', 'composer-setup.php') === '8a6138e2a05a8c28539c9f0fb361159823655d7ad2deecb371b04a83966c61223adc522b0189079e3e9e277cd72b8897') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
sudo php composer-setup.php
sudo php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer
`
I would really  like to know the underlying problem as we have quite a few automated updates on hold now so that we don't have offline sites.

**Comment by davidvandertuijn** [comment] 2020-09-11 09:36
same issue, `composer self-update` does not fix it.
recently i have also discovered issues with packagist and changed to a mirror.

switch to mirror:
`composer config -g repos.packagist composer https://packagist.fi`

switch back to official:
`composer config -g repos.packagist composer https:/repo.packagist.org`

check global config:
`composer config -g -l`

but in this case, i think it has something todo with the latest release of Purifier.
how to solve it?

**Comment by GJPhilippi** [comment] 2020-09-11 18:06
Just to confirm, switching to the correct `composer` version fixed it for me too!

**Comment by ppalella** [comment] 2020-09-14 21:43
Same issue! :(

**Comment by KeithTurkowski** [comment] 2020-09-15 02:38
If you delete the vendor directory, then you can remove purifier from composer.json and run `composer install` to fix the problem, although this will remove Purifier from your project.

**Comment by mrbenosborne** [comment] 2020-09-21 10:24
Same here, any update on when this will be fixed?

**Comment by ibeona** [comment] 2020-10-05 12:53
Same problem here and the composer self-update didn't fix it.

**Comment by GJPhilippi** [comment] 2020-10-05 12:57
I was able to solve the issue by switching to the correct build of Composer instead of using the version available on my OS (Kubuntu). I had to reinstall composer manually for it, @ibeona @mrbenosborne.

First uninstall the OS-installed version (in *buntu `apt remove --purge composer`) and then install the correct one from https://getcomposer.org/

**Comment by ibeona** [comment] 2020-10-05 13:00
@GJPhilippi i've tested composer 1.9 and composer 1.10,  i'm in a docker container. I've tested by building the container with both versions but same error each time :( .  
Or do i have to switch to composer 2.0 ?

**Comment by GJPhilippi** [comment] 2020-10-05 13:47
@ibeona No, Composer 2.0 isn't publicly available, so you shouldn't switch to it. I use `Composer version 1.10.13 2020-09-09 11:46:34`, without a Docker container and works perfectly fine.

**Comment by ibeona** [comment] 2020-10-05 13:53
> @ibeona No, Composer 2.0 isn't publicly available, so you shouldn't switch to it. I use `Composer version 1.10.13 2020-09-09 11:46:34`, without a Docker container and works perfectly fine.

Ok, i tried with composer 1.10.13 in docker tag still not working but i'll investigate and search about docker issue so ! 
Thank you for your time!

**Closed** 2023-10-16 14:27 UTC
